#ifndef LIBLEIDENALG_C_API_H
#define LIBLEIDENALG_C_API_H

#include "libleidenalg_export.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum
{
  LIBLEIDENALG_OK = 0,
  LIBLEIDENALG_ERR_INVALID_ARGUMENT = 1,
  LIBLEIDENALG_ERR_IGRAPH = 2,
  LIBLEIDENALG_ERR_INTERNAL = 3
};

/**
 * Run Leiden modularity optimisation on an edge list.
 *
 * edges is expected to have exactly edge_count * 2 entries:
 * [from0, to0, from1, to1, ...]
 */
LIBLEIDENALG_EXPORT int libleidenalg_modularity_partition(
  int64_t vertex_count,
  int64_t edge_count,
  const int64_t* edges,
  int directed,
  uint64_t seed,
  int64_t* membership_out,
  int64_t membership_len,
  double* quality_out
);

/** Returns the last error message generated by the C API. */
LIBLEIDENALG_EXPORT const char* libleidenalg_last_error(void);

#ifdef __cplusplus
}
#endif

#endif // LIBLEIDENALG_C_API_H
